config/routes.rb
Dota::Application.routes.draw do
   root to: 'pages#index'

   get '/login', to: 'sessions#new'
   post '/login', to: 'sessions#create'
   get '/logout', to: 'sessions#delete'
   post 'logout', to: 'sessions#delete'

  resources :heroes
  resources :searches, only: [:show, :create]
  resources :users
  resources :drafts, only: [:create, :new, :show, :edit, :index]
  resources :user_searches, only: [:show, :create]


  get 'sign_up' => 'users#new'


  get  "/users/forgot_password" => "users#forgot_password",
    as: "forgot_password"
  post "/users/forgot_password" => "users#forgot_password_post",
    as: "forgot_password_post"
  get  "/users/reset_password/:user_id/:token" => "users#reset_password",
    as: "reset_password"
  post "/users/reset_password" => "users#reset_password_post",
    as: "reset_password_post"

end

app/models/draft.rb
class Draft < ActiveRecord::Base
  belongs_to :user

  has_many :draft_picks
  has_many :draft_bans
  has_many :picks, through: :draft_picks #source: :hero
  has_many :bans, through: :draft_bans #source: :hero

  validates :user, presence: true

  def initialize(user1, user2)
    @user1 = user1
    @user2 = user2
    @bans_for_user1 = []
    @bans_for_user2 = []
    @picks_for_user1 = []
    @picks_for_user2 = []
    @level = 1
  end

  def ban_for_user1(hero)
    @bans_for_user1 << hero

  end

  def ban_for_user2(hero)
    if !@bans_for_user1.include?(hero)
      @bans_for_user2 << hero
    end
  end

  def bans_for_user1
    @bans_for_user1
  end

  def bans_for_user2
    @bans_for_user2
  end

  def pick_for_user1(hero)
    @picks_for_user1 << hero
  end

  def pick_for_user2(hero)
    @picks_for_user2 << hero
  end

  def picks_for_user1
    @picks_for_user1
  end

  def picks_for_user2
    @picks_for_user2
  end

  def advance?
    @bans_for_user1.length == @bans_for_user2.length
  end

end

app/models/draft_ban.rb
class DraftBan < ActiveRecord::Base
  belongs_to :draft
  belongs_to :hero

  validates :draft, presence: true
  validates :hero, presence: true
end

app/models/draft_pick.rb
class DraftPick < ActiveRecord::Base
  belongs_to :draft
  belongs_to :hero

  validates :draft, presence: true
  validates :hero, presence: true
end

app/models/hero.rb
class Hero < ActiveRecord::Base
	has_attached_file :thumbnail
  validates_attachment_content_type :thumbnail, :content_type => %w(image/png)
  validates :name, :summary, :hero_type, :presence => true
end

app/models/search.rb
class Search < Struct.new(:name)
	def heroes
		@heroes = Hero.where("name ILIKE ?", "%#{name}%")
	end
end

app/models/session.rb
class Session <  ActiveRecord::Base
  validates :email, presence: {messsage: "Email must not be blank"}
  validates :password_digest, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base
	  has_many :drafts
	  validates :email, :first_name, :last_name, :username, presence: true
    validates :email, uniqueness: true
    has_secure_password
end

app/models/user_search.rb
class UserSearch < Struct.new(:username)
  def users
    @users ||= User.where("username ILIKE ?", "%#{username}%")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 # protect_from_forgery with: :exception

  def index

    @user_id = User.find(session[:user_id])

  end

end

app/controllers/drafts_controller.rb
class DraftsController < ApplicationController


	def new
    @user1 = params[:user_1]
    @user2 = params[:user_2]
    @starting_heroes = Hero.all
    @level = 1
		@draft = Draft.new

  end


	def create
    @heroes = Hero.all
		@draft  = Draft.create(@heroes)

	  if @draft.save
      flash[:success] = "Your draft has been saved"
			redirect_to heroes_path
    else
      render :new and return
    end
  end

  def edit
		@hero = hero
	end

  def ensure_length_of_picks
    if picks.size > 5
      errors.add(:picks, 'Cannot pick more than 5 heroes')
    end
  end

  def ensure_length_of_bans
    if bans.size > 5
      errors.add(:bans, 'Cannot ban more than 5 heroes')
    end
  end
end

app/controllers/heroes_controller.rb
class HeroesController < ApplicationController
	helper_method :heroes, :hero
	respond_to :html
  def index
    if session[:user_id]
      @user_id = User.find(session[:user_id])
    end
  end
	def new
		@hero = Hero.new
	end

	def create

     if  @hero = Hero.create(hero_params)
		respond_with @hero
     else
    render :new
    end
	end

	def edit
		@hero = hero
	end

	def update
		@hero = hero
		hero.update_attributes(hero_params)
		respond_with @hero
	end

	def destroy
		hero.destroy
		redirect_to heroes_path
	end

	private

	def hero_params
		params.require(:hero).permit(:name, :summary, :hero_type, :thumbnail)
	end

	def heroes
		@_heroes ||= Hero.all
	end

	def hero
		@_hero ||= Hero.find(params[:id])
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def show

  end

  def index
    if session[:user_id]
    @user_id = User.find(session[:user_id])
    end


    end

end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController


  def create
    redirect_to search_path(params[:search][:name])
  end

  def show
    if session[:user_id]
      @user_id = User.find(session[:user_id])
      @heroes = Search.new(params[:id]).heroes
    else
      redirect_to '/', notice: "Users only can access this page"
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new

  end

  def create
    email = params[:email]
    password = params[:password]
    current_user = User.where(:email => email).first

    if email.strip.empty? || current_user == nil
      redirect_to login_path, notice: "Email or password were incorrect"

    elsif current_user.password_digest == password

      session[:user_id] = current_user.id
      redirect_to '/'
    else
      @notice = "Email or Password is incorrect"
      render :new
    end
  end

  def delete
    session[:user_id] = nil
    redirect_to root_path, notice: "You have succesfully logged out"
  end
end

app/controllers/user_searches_controller.rb
class UserSearchesController < ApplicationController

  def create
    redirect_to user_search_path(params[:user_search][:username])
  end

  def show
    if session[:user_id]
      @user_id = User.find(session[:user_id])
      @users = UserSearch.new(params[:id]).users
    else
   redirect_to '/', notice: "Only Users can access this page"
  end
end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  helper_method :users, :user
  respond_to :html



  def index
    if session[:user_id]
      @user_id = User.find(session[:user_id])
    end
      redirect_to '/', notice: "Users only can access this page"
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: "User Created"
    else
      render :new
    end
  end
  def show
    @user = User.find(params[:id])
  end

  private
  def user_params
    params.require(:user).permit(:username, :first_name, :last_name, :email, :password_digest)
  end

  def users
    User.all
  end

  def user
    User.find(params[:id])
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/drafts/index.html.erb
<p> INDEX Draft </p>

app/views/drafts/new.html.erb
<h1>New Draft</h1>
<table>
  <tbody>
  <% @heroes.each do |hero| %>
    <tr>
      <td>
        <button name="hero_id" value="<%= hero.id %>"> <%= image_tag hero.thumbnail.url, width: 50, height: 50 %> </button>
      </td>
  <% end %>
  </tbody>
</table>

app/views/heroes/_form.html.erb
<%= form_for @hero do |form| %>
  <table>
    <tr>
      <td><%= form.label :name %></td>
      <td>
        <%= form.text_field :name %>
      </td>
    </tr>
    <tr>
      <td><%= form.label :summary %></td>
      <td>
        <%= form.text_area :summary, rows: 6, cols: 100 %>
      </td>
    </tr>
    <tr>
      <td><%= form.label :hero_type %></td>
      <td>
       <%= form.select :hero_type, 
       options_for_select(["Carry", "Support", "Mid", "Offlane"]), 
       prompt: "Choose a Hero Type" %>
      </td>
    </tr>
    <tr>
      <td><%= form.label :thumbnail %></td>
      <td><%= form.file_field :thumbnail %></td>
    </tr>
    <tr>
      <td></td>
      <td>
        <%= form.submit "Save" %>
      </td>
    </tr>
  </table>
<% end %>

app/views/heroes/edit.html.erb
<h1>Edit Hero</h1>
<%= render 'form' %>

app/views/heroes/index.html.erb
<h1>A list of all Heroes in Dota 2</h1>
<table>
	<thead>
		<th>Name</th>
		<th></th>
		<th></th>
	</thead>
	<tbody>
		<% heroes.each do |hero| %>
			<tr>
			  <td>
			    <%= link_to hero.name, hero %>
			  </td>
			  <td><%= image_tag hero.thumbnail.url %></td>
			  <td>
			  	<%= link_to "Edit", edit_hero_path(hero) %>
			  </td>
			  <td>
			  	<%= link_to "Delete", hero, method: :delete, confirm: "Are you sure?" %>
			  </td>
			</tr>  
		<% end %>
	</tbody>
</table>
<%= link_to "Add Hero", new_hero_path %>
<div class="navbar">
		Search Heroes <%= form_for :search, url: searches_path do |form| %>
			<%= form.text_field :name %>
		<% end %>
</div>

app/views/heroes/new.html.erb
<h1>Add a Hero</h1>
<% @hero.errors.full_messages.each do |error| %>
  <li><%= error %></li>
<% end %>

<%= render 'form' %>

app/views/heroes/show.html.erb
<b>Name</b>
<br>
<%= hero.name %>

<p>
  <b>Summary</b>
  <br>
  <%= hero.summary %>
</p>
<p>Hero Type</p>
<%= hero.hero_type %>
<p>Image
  <button name="hero_id" value="<%= hero.id %>"> <%= image_tag hero.thumbnail.url, width: 100, height: 100 %> </button>
</p>
<p><%= link_to "Edit", edit_hero_path(hero.id) %> </p>

<p><%= link_to "New", new_hero_path %> </p>

<p><%= link_to "Back", heroes_path %> </p>

<p><%= link_to "Delete", hero, method: :delete, confirm: "Are you sure?" %></p>


<div class="navbar">
  <%= form_for :search, url: searches_path do |form| %>
    <%= form.text_field :name %>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>


<head>
  <style id="_sl_hide" type="text/css">body { display: none; }</style>
  <script src="https://fightforthefuture.github.io/stoptheslowlane/widget/slowlane.js"></script>

  <title>Dota</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>

<body>
<%= notice %>
<% if @user_id %>
  <li>Welcome, <%= @user_id.email  %></li>
  <li> <%= link_to "Logout", logout_path %></li>

<% end %>


<%= yield %>

</body>
</html>

app/views/pages/index.html.erb
<h1>Dota 2 Heroes</h1>



<p>This is a database for accessing all of the heroes in Defense of the Ancients 2</p>
<ul>
  <li><%= link_to "All Heroes", heroes_path %></li>

  <% if @user_id.nil? %>
  <li> <%= link_to "Create Account", sign_up_path %></li>
    <% end %>
  <% if @user_id %>
  <li>  <%= link_to "New Draft", new_draft_path %></li>
  <li>  <%= link_to "All Users", users_path %></li>
    <% end %>
  <% if @user_id.nil? %>
  <li>  <%= link_to "Login", login_path %></li>
    <% end %>
</ul>
<br>

<% if @user_id %>

<p> To search for users type username here: </p>
<div class="navbar">
  <%= form_for :user_search, url: user_searches_path do |form| %>
    <%= form.text_field :username %>
  <% end %>
</div>

<br>
<p>To Search by individual heroes type name here</p>
<div class="navbar">
  <%= form_for :search, url: searches_path do |form| %>
    <%= form.text_field :name %>
  <% end %>
</div>
<% end %>

app/views/searches/show.html.erb
<h1>Search Results</h1>
<table>
  <thead>
  <th>Name</th>
  </thead>
  <tbody>
  <% @heroes.each do |hero| %>
    <tr>
      <td><%= hero.name %> </td>
      <td><%= image_tag hero.thumbnail.url %></td>
      <td><%= link_to "Edit", edit_hero_path(hero) %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/user_searches/show.html.erb
<h1>Search Results</h1>
<table>
	<thead>
		<th>Username</th>
</thead>
	<tbody>
		<% @users.each do |user| %>
			<tr>
				<td><%= user.username %> </td>
        <td><%= link_to "Show", user_path(user) %></td>
			</tr>
<% end %>
  </tbody>
</table>

app/views/users/_form.html 19-15-18-397.erb
  <table>
    <tr>
      <td><%= form.label :username %></td>
      <td><%= form.text_field :username %></td>
    </tr>
    <tr>
      <td><%= form.label :password_digest %></td>
      <td><%= form.password_field :password %> </td>
    </tr>
    <tr>
      <td><%= form.label :first_name %>
      <td><%= form.text_field :first_name %></td>
    </tr>
    <tr>
      <td><%= form.label :last_name %></td>
      <td><%= form.text_field :last_name %></td>
    <tr>
      <td><%= form.label :email %></td>
      <td><%= form.text_field :email %></td>
    </tr

    <tr>
      <td>
      <%= form.submit "Create" %>
      </td>
    </tr>
  </table>

app/views/users/forgot_password.html.erb
<%= form_tag forgot_password_post_path do %>
  <p>
    Please enter the email address<br>
    that you originally registered with:
  </p>
  <p><%= text_field_tag "email_address" %></p>
  <p><%= submit_tag "Send password reset" %></p>
<% end %>

app/views/users/index.html.erb
<h1>All Users</h1>
<table>
  <tbody>
  <% users.each do |user| %>
    <tr>
      <td><%= link_to user.username, user %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<% @user.errors.full_messages.each do |error| %>
  <li><%= error %></li>
<% end %>


<%= form_for @user do |form| %>

<h1>Create Account</h1>
 <table>
    <tr>
      <td><%= form.label :username %></td>
      <td><%= form.text_field :username %></td>
    </tr>
    <tr>
      <td><%= form.label :password%></td>
      <td><%= form.password_field :password_digest %> </td>
    </tr>
    <tr>
      <td><%= form.label :first_name %>
      <td><%= form.text_field :first_name %></td>
    </tr>
    <tr>
      <td><%= form.label :last_name %></td>
      <td><%= form.text_field :last_name %></td>
    <tr>
      <td><%= form.label :email %></td>
      <td><%= form.text_field :email %></td>
    </tr
    <tr>
      <td><%= form.submit "Create" %> </td>
    </tr>
  </table>

<% end %>
	

app/views/users/reset_password.html.erb
<h1>Reset password for <%= @user.email_address %></h1>

<%= error_messages_for @user %>

<%= form_tag reset_password_post_path do %>
  <p>
    <%= label_tag :password %><br>
    <%= password_field_tag :password %>
  </p>

  <p>
    <%= submit_tag "Reset password" %>
  </p>
<% end %>

app/views/users/show.html.erb
<h1> <%= user.username %> </h1>

<table>

  <tr>
    <td> <%= user.first_name %> </td>
    <td> <%= user.last_name %> </td>
    <td> <%= user.email %> </td>
  </tr>



</table>